default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV["DB_USER"].presence || ENV.fetch("USER", "postgres") %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  variables:
    statement_timeout: <%= ENV.fetch("DB_STATEMENT_TIMEOUT", 5000) %>

development:
  primary: &primary_development
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "food_mapp_development") %>
  queue:
    <<: *primary_development
    database: <%= ENV.fetch("DB_QUEUE_NAME", "food_mapp_development_queue") %>
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.rb

test:
  primary: &primary_test
    <<: *default
    database: <%= ENV.fetch("DB_TEST_NAME", "food_mapp_test") %>
  queue:
    <<: *primary_test
    database: <%= ENV.fetch("DB_QUEUE_TEST_NAME", "food_mapp_test_queue") %>
    migrations_paths: db/queue_migrate
    schema_dump: queue_schema.rb

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "food_mapp_production") %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DB_CACHE_NAME", "food_mapp_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DB_QUEUE_NAME", "food_mapp_production_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DB_CABLE_NAME", "food_mapp_production_cable") %>
    migrations_paths: db/cable_migrate
